version: "3"

services:
  postrussia:
    build: .
    image: discord-musicbot:latest
    container_name: postrussia
    restart: unless-stopped
    networks:
      - lavalink-net
    depends_on:
      - lavalink
    volumes:
      - ./botconfig.js:/usr/src/app/botconfig.js:ro

  lavalink:
    image: fredboat/lavalink:dev
    container_name: music-lavalink
    hostname: lavalink
    restart: unless-stopped
    networks:
      - lavalink-net
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro

networks:
  lavalink-net: